syntax = "proto3";

package ui;


message Empty {
}

message GetRequest {
    uint32 history = 1; // How many history seconds to return (0 = all retained).
    uint32 end_timestamp = 2; // Inclusive end in Unix seconds (0 = now).
  }

message Metric {
  uint32 timestamp = 1;
  uint32 ok = 2;
  uint32 nok = 3;
}

message GetResponse {
   repeated Metric metrics = 1;
   uint32 retention = 2;
}

// Interface exported by the server.
service UI {
    rpc Get(GetRequest) returns (GetResponse) {}
    rpc Subscribe(Empty) returns (stream Metric) {}
  }
  